#!/bin/bash

old_1=0
old_2=0
old_3=0
old_4=0
old_5=0
old_6=0
count=1

while [ "$old_6" -le "6" ]  
do

	old_1=$(($old_1+1))	

	if [ "$(($count%7))" -eq "0" ]
	then
		old_1=0
		old_2=$(($old_2+1))
	fi

	if [ "$(($count%49))" -eq "0" ]
	then
		old_1=0
		old_2=0
		old_3=$(($old_3+1))
	fi

	if [ "$(($count%343))" -eq "0" ]
	then
		old_1=0
		old_2=0
		old_3=0
		old_4=$(($old_4+1))
	fi

        if [ "$(($count%2401))" -eq "0" ]
        then
		old_1=0
		old_2=0
		old_3=0
		old_4=0
		old_5=$(($old_5+1))
        fi

        if [ "$(($count%16807))" -eq "0" ]
        then
		old_1=0
		old_2=0
		old_3=0
		old_4=0
		old_5=0
		old_6=$(($old_6+1))
		echo "$old_6"
        fi

	count=$(($count+1))

	newline="$old_6 $old_5 $old_4 $old_3 $old_2 $old_1"
	echo "$newline"
	sed -i "6s/.*/$newline/" answers_3.txt	
	
	
	gdb --command=gdb_commands_3 bomb	

done
exit 0
