#!/bin/bash

old_1=0
old_2=0
old_3=0
old_4=0
old_5=1
old_6=0
count=1

while [ "$old_6" -le "20" ]  
do

	old_1=$(($old_1+1))	

	if [ "$(($count%20))" -eq "0" ]
	then
		old_1=0
		old_2=$(($old_2+1))
	fi

	if [ "$(($count%400))" -eq "0" ]
	then
		old_1=0
		old_2=0
		old_3=$(($old_3+1))
	fi

	if [ "$(($count%8000))" -eq "0" ]
	then
		old_1=0
		old_2=0
		old_3=0
		old_4=$(($old_4+1))
	fi

        if [ "$(($count%160000))" -eq "0" ]
        then
		old_1=0
		old_2=0
		old_3=0
		old_4=0
		old_5=$(($old_5+1))
        fi

        if [ "$(($count%3200000))" -eq "0" ]
        then
		old_1=0
		old_2=0
		old_3=0
		old_4=0
		old_5=1
		old_6=$(($old_6+1))
		echo "$old_6"
        fi

	count=$(($count+1))

	newline="$old_6 $old_5 $old_4 $old_3 $old_2 $old_1"
	echo "$newline"
	sed -i "2s/.*/$newline/" answers_2.txt	
	
	
	gdb --command=gdb_commands_2 bomb	

done
exit 0
